all:
	../../huangyilib/s5/rst2s5.py _2012-03-25_obviously-correct-code.rst slide.html
	#rst2odp _2012-03-25_obviously-correct-code.rst slide.odp
	#../../huangyilib/s5/rst2s5.py _obviously-correct2.rst slide2.html
